"""Add large binary to store music data file

Revision ID: 92ed8f037e0b
Revises: 990340bed244
Create Date: 2023-12-07 17:09:45.134786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ed8f037e0b'
down_revision: Union[str, None] = '990340bed244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('music_file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'music_file')
    # ### end Alembic commands ###
