# Generated by Django 4.2.7 on 2023-12-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='Image_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='fruits.category'),
            preserve_default=False,
        ),
    ]
