# Generated by Django 4.2.4 on 2023-10-30 08:12

from django.db import migrations


def set_age_groups(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()

    for person in persons:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

    person_model.objects.bulk_update(persons, ['age_group'])


def set_age_groups_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()
    age_group_default = person_model._meta.get_field('age_group').default

    for person in persons:
        person.age_group = age_group_default
    
    person_model.objects.bulk_update(persons, ['age_group'])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_groups, reverse_code=set_age_groups_default)
    ]
